### ISSUE TITLE
Nutshell: volume creation fails (affects Galera and XtreemFS)

### ISSUE THREAD

**Issue by tcrivat** [ConPaaS-team/conpaas#73]
In the nutshell, both the Galera and the XtreemFS services fail to start because the creation of a new volume fails with "Unknown error".

Relevant logs from Galera:

2014-10-01 10:30:18,222 DEBUG conpaas.core.manager trying to create a volume for the node_id=i-0000005b
2014-10-01 10:30:18,222 INFO conpaas.core.manager Creating a volume named galera-172.16.0.226 (1024 MBs)
2014-10-01 10:30:18,222 DEBUG conpaas.core.controller create_volume(cloud=iaas, size=1024, name='galera-172.16.0.226')
2014-10-01 10:30:19,614 DEBUG conpaas.core.controller [delete_nodes]: killing iaasi-0000005b
2014-10-01 10:30:19,615 DEBUG ReservationTimer RTIMER removed node iaasi-0000005b, updated list []
2014-10-01 10:30:19,615 DEBUG ReservationTimer RTIMER Stopping timer for []
2014-10-01 10:30:19,615 DEBUG conpaas.core.clouds.base kill_instance(node=ServiceNode(id=iaasi-0000005b, ip=172.16.0.226))
2014-10-01 10:30:20,278 ERROR conpaas.core.manager do_startup: Failed to request a new node on cloud iaas: OverQuota: Unknown error occurred..
Traceback (most recent call last):
  File "/root/ConPaaS/src/conpaas/services/galera/manager/manager.py", line 93, in _do_startup
    self._start_mysqld(node_instances)
  File "/root/ConPaaS/src/conpaas/services/galera/manager/manager.py", line 112, in _start_mysqld
    volume = self.create_volume(1024, volume_name,node_id)
  File "/root/ConPaaS/src/conpaas/core/manager.py", line 212, in create_volume
    volume = self.controller.create_volume(size, name, vm_id, cloud)
  File "/root/ConPaaS/src/conpaas/core/controller.py", line 498, in create_volume
    return cloud.create_volume(size, name, vm_id)
  File "/root/ConPaaS/src/conpaas/core/clouds/base.py", line 196, in create_volume
    return self.driver.create_volume(size, name)
  File "/root/ConPaaS/contrib/libcloud/compute/drivers/ec2.py", line 689, in create_volume
    self.connection.request(self.path, params=params).object,
  File "/root/ConPaaS/contrib/libcloud/common/base.py", line 609, in request
    connection=self)
  File "/root/ConPaaS/contrib/libcloud/common/base.py", line 93, in __init__
    raise Exception(self.parse_error())
Exception: OverQuota: Unknown error occurred.

Relevant logs from XtreemFS:

2014-10-01 10:50:47,721 INFO conpaas.core.manager Creating a volume named osd-cd3ca532-4958-11e4-b3eb-fa163eaf90f6 (1024 MBs)
2014-10-01 10:50:47,722 DEBUG conpaas.core.controller create_volume(cloud=iaas, size=1024, name='osd-cd3ca532-4958-11e4-b3eb-fa163eaf90f6')
2014-10-01 10:50:48,688 DEBUG conpaas.core.controller [delete_nodes]: killing iaasi-0000005d
2014-10-01 10:50:48,688 DEBUG ReservationTimer RTIMER removed node iaasi-0000005d, updated list []
2014-10-01 10:50:48,688 DEBUG ReservationTimer RTIMER Stopping timer for []
2014-10-01 10:50:48,688 DEBUG conpaas.core.clouds.base kill_instance(node=ServiceNode(id=iaasi-0000005d, ip=172.16.0.226))
2014-10-01 10:50:50,260 ERROR conpaas.core.manager do_startup: Failed to request a new node
Traceback (most recent call last):
  File "/root/ConPaaS/src/conpaas/services/xtreemfs/manager/manager.py", line 291, in _do_startup
    self._start_osd(self.osdNodes, startCloud)
  File "/root/ConPaaS/src/conpaas/services/xtreemfs/manager/manager.py", line 211, in _start_osd
    node.vmid, cloud)
  File "/root/ConPaaS/src/conpaas/core/manager.py", line 212, in create_volume
    volume = self.controller.create_volume(size, name, vm_id, cloud)
  File "/root/ConPaaS/src/conpaas/core/controller.py", line 498, in create_volume
    return cloud.create_volume(size, name, vm_id)
  File "/root/ConPaaS/src/conpaas/core/clouds/base.py", line 196, in create_volume
    return self.driver.create_volume(size, name)
  File "/root/ConPaaS/contrib/libcloud/compute/drivers/ec2.py", line 689, in create_volume
    self.connection.request(self.path, params=params).object,
  File "/root/ConPaaS/contrib/libcloud/common/base.py", line 609, in request
    connection=self)
  File "/root/ConPaaS/contrib/libcloud/common/base.py", line 93, in __init__
    raise Exception(self.parse_error())
Exception: OverQuota: Unknown error occurred.

**Comment by tcrivat** [comment]
This is now fixed in the latest version of the Nutshell (1.5.0).
